In [1]:
import os
os.getcwd()

'd:\\123cs0061'

## Set Union

In [4]:
n = int(input())
s1 = set(map(int, input().split()))
m = int(input())
s2 = set(map(int, input().split()))
s3 = s1.union(s2)
print(len(s3))

5


## Set Intersection Count

In [6]:
n = int(input())
s1 = set(input().split())
m = int(input())
s2 = set(input().split())
s3 = s1.intersection(s2)
print(len(s3))

1


## Set Symmetric Difference

In [ ]:
s1 = set(map(int, input().split()))
s2 = set(map(int, input().split()))
s3 = s1.symmetric_difference(s2)
s3.sort()
for x in s3:
    print(x)

3
4
5
6
7
8


## Check Subset

In [8]:
n = int(input())
s1 = set(input().split())
m = int(input())
s2 = set(input().split())
issub = s1.issubset(s2)
if issub:
    print("A is a subset of B")
else:
    print("A is not a subset of B")

A is a subset of B


## Set Difference

In [15]:
n = int(input())
s1 = list(map(int, input().split()))
s1.sort()
m = int(input())
s2 = list(map(int, input().split()))
s2.sort()
s1, s2 = set(s1), set(s2)
diff = (s1.difference(s2))
for x in diff:
    print(x)

1
3
5


# Numpy Coding Problems

## Array Manipulation with Numpy

In [21]:
import numpy as np
n = int(input())
arr = np.array(list(map(int, input().split())))
for i, x in enumerate(arr):
    if arr[i]%2:
        arr[i] = (x/2)
    else:
        arr[i] = (x*2)
print(arr)

[ 4  1  8  2 12]


## Matrix Diagonal Sum Using Numpy

In [28]:
n = int(input())
arr = []
for _ in range(n):
    temp = list(map(int, input().split()))
    arr.append(temp)
leftsum, rightsum = 0, 0
for i in range(n):
    for j in range(n):
        if i == j:
            leftsum += arr[i][j]
        if i + j == n - 1:
            rightsum += arr[i][j]
print(abs(leftsum - rightsum))

15


## Reshape Array using Numpy 

In [ ]:
import numpy as np
n, r, c = map(int, input().split())
arr = np.array(list(map(int, input().split())))
new = arr.reshape((r, c))
print(new)

[[1 2 3]
 [4 5 6]]


## Element Wise Operations on Two Arrays

In [32]:
import numpy as np
n = int(input())
x = np.array(list(map(int, input().split())))
y = np.array(list(map(int, input().split())))
print(x + y)
print(x - y)
print(x * y)
print( x // y)

[ 3  6  9 12]
[1 2 3 4]
[ 2  8 18 32]
[2 2 2 2]


## Find Unique Elements Using Numpy 

In [35]:
import numpy as np
n = int(input())
arr = np.array(list(map(int, input().split())))
print(np.unique(arr))

[4 5 6 7 8 9]


In [37]:
import numpy as np

n = int(input())
arr = np.array(list(map(int, input().split())))
threshold = int(input())
mask = arr > threshold
res = []
for i, val in enumerate(mask):
    if val:
        res.append(int(arr[i]))
print(res)

[10, 15, 8]
